services:
  app:
    build: .
    container_name: ci3_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: codeigniter_test
      DB_USER: postgres
      DB_PASS: postgres
    restart: always

  postgres:
    image: postgres:18
    container_name: ci3_db
    environment:
      POSTGRES_DB: codeigniter_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql:ro
      - pg_data:/var/lib/postgresql
    restart: always

volumes:
  pg_data: